apiVersion: v1
kind: Service
metadata:
  name: {{ include "sensorsqc.fullname" . }}
  labels:
    {{- include "sensorsqc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name}}
  selector:
    {{- include "sensorsqc.selectorLabels" . | nindent 4 }}
